logging: aim
env_params:
  env_name: "brax-halfcheetah"
  batch_size: 64
  init_kwargs:
    backend: "spring"
trace_mode: "accumulate"
gamma: 0.99
lambda_v: 0.99
lambda_pi: 0.99
lambda_rnn: 0.99
# eta_pi: "1e-3"
# eta_f: "1e-2"
entropy_rate: 1e-5
steps: 1000
eval_every: 100
pass_obs: false
optimizer_params_td:
  # decay_type: cosine
  learning_rate: "1e-3"
optimizer_params_rnn:
  # decay_type: cosine
  learning_rate: "1e-3"
